spring.application.name=chase

#H2 config
spring.datasource.url=jdbc:h2:mem:chasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#JPA config

#//springdata jpa automatically start creating database
spring.jpa.hibernate.ddl-auto=update 
#can see it printed out
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#JWT config 
jwt.secret=XZ3Qvno8dL9EMW17St0gEcns33LpTWr2Yvx
jwt.expiration=86400000 
#expire 24 hrs, require relogin after 


